// <auto-generated />
using System;
using ECA.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECA.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECA.API.Models.ComputerUser", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UserId"));

                    b.Property<decimal?>("CDLRIsn")
                        .HasColumnType("numeric");

                    b.Property<int?>("DDBIdentification")
                        .HasColumnType("int");

                    b.Property<decimal?>("EMPID")
                        .HasColumnType("numeric");

                    b.Property<int?>("GEMPDDBIdentification")
                        .HasColumnType("int");

                    b.Property<decimal?>("GEMPIsn")
                        .HasColumnType("numeric");

                    b.Property<short?>("Rsc")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("SYSWSIsn")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UserEventsLoggingBeginDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UserEventsLoggingEndDT")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UserEventsLoggingFlag")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UserLastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UserLastLogoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("UserPasswordEncrypted")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("UserPasswordEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UserPasswordTypeCode")
                        .HasColumnType("numeric");

                    b.Property<string>("UserRemarks")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<short?>("UserWorkStValidateFlag")
                        .HasColumnType("smallint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("UserId");

                    b.HasIndex("SYSWSIsn");

                    b.ToTable("ComputerUser");
                });

            modelBuilder.Entity("ECA.API.Models.SystemWorkstation", b =>
                {
                    b.Property<decimal>("SYSWSIsn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("SYSWSIsn"));

                    b.Property<decimal?>("CCPXIsn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CDIsn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CUSTIsn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CshrIsn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DCRTNIsn")
                        .HasColumnType("numeric");

                    b.Property<int>("DDBIdentification")
                        .HasColumnType("int");

                    b.Property<decimal?>("GATEIsn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OLD_DCRTNIsn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short?>("Rsc")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("STOREIsn")
                        .HasColumnType("numeric");

                    b.Property<string>("SYSWSArabicName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SYSWSIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SYSWSInstallationPlace")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SYSWSPurpose")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<short>("SYSWSWorkTypeCode")
                        .HasColumnType("smallint");

                    b.Property<int?>("UnitCode")
                        .HasColumnType("int");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WRHSEIsn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WTSTIsn")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SYSWSIsn");

                    b.ToTable("SystemWorkstations");
                });

            modelBuilder.Entity("ECA.API.Models.ComputerUser", b =>
                {
                    b.HasOne("ECA.API.Models.SystemWorkstation", "SystemWorkstation")
                        .WithMany("ComputerUsers")
                        .HasForeignKey("SYSWSIsn");

                    b.Navigation("SystemWorkstation");
                });

            modelBuilder.Entity("ECA.API.Models.SystemWorkstation", b =>
                {
                    b.Navigation("ComputerUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
